name: Build and Deploy Gatsby

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Gatsby site
        run: npm run build

      - name: Add CNAME file
        run: echo "moonjarstudio.com" > public/CNAME

      - name: Deploy to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/
          git commit -m "Update built site [skip ci]" || echo "No changes to commit"
          git push origin main
